platform :ios, '6.0'

pod 'Reachability'
pod 'SBJson'
pod 'TouchXML'
pod 'SVGeocoder'
pod 'AFNetworking','1.3.2'
pod 'JSONModel'

#pod 'JSONKit'
#pod 'DPToastView'
#pod 'LocationHelper'
#pod 'InternetReachable'
#pod 'InfColorPicker'
#pod 'CustomBadge'
#pod 'SFHFKeychainUtils'
#pod 'NSString+Emoji'
#pod 'FMDB'
#pod 'skpsmtpmessage'
